### ISSUE TITLE
PEP 318 Examples 4 the order of @accepts and @returns maybe wrong

### ISSUE THREAD

**Issue by chenyangdream** [python/peps#910]
Example 4 
@accepts(int, (int,float))
@returns((int,float))
def func(arg1, arg2):
    return arg1 * arg2

The order of @accepts and @returns should be reversed, otherwise, the assertion will be raised.

```
Traceback (most recent call last):
  File "/Users/jack/PycharmProjects/tutorial/testdecorator.py", line 25, in <module>
    @returns((int,float))
  File "/Users/jack/PycharmProjects/tutorial/testdecorator.py", line 3, in check_accepts
    assert len(types) == f.func_code.co_argcount
AssertionError
```

**Comment by AA-Turner** [comment]
There's been no activity here for three years, closing. If still relevant a PR could be reviewed.
A
